
export const metadata = {
    title: 'Doctores | Clinica CPH Salud',
    description: 'Generated by create next app',
}

export default function DoctoresLayout({
    children,
}) {
    return (
        <section>
            {children}
        </section>
    );
}