export const metadata = {
    title: 'Bioseguridad | Clinica CPH Salud',
    description: 'Generated by create next app',
}

export default function BioseguridadLayout({
    children,
}) {
    return (
        <section>
            {children}
        </section>
    );
}