export const metadata = {
    title: 'Informacion al paciente | Clinica CPH Salud',
    description: 'Generated by create next app',
}

export default function InformacionPacienteLayout({
    children,
}) {
    return (
        <section>
            {children}
        </section>
    );
}